sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

before_script:
  - npm run init

script:
  - npm test
  - npm audit

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"

branches:
  only:
    - develop
